name: Test 7.x-1.x Docker and Drush Make builds
on:
  push:
    branches:
      - '7.x-1.x'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Set FARMOS_BRANCH environment variable
        run: echo ::set-env name=FARMOS_BRANCH::${GITHUB_REF:11}
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --output "type=image,push=false" \
            --build-arg FARMOS_REPO=https://github.com/${GITHUB_REPOSITORY} \
            --build-arg FARMOS_BRANCH=${FARMOS_BRANCH} \
            --file ./docker/dev/Dockerfile ./
